exp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import views
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
import settings

urlpatterns = [
    url(r'^plataforma/', include(admin.site.urls)),
    url(r'^usuario/', include('usuario.urls', namespace='usuario')),
    url(r'^motorizado/', include('motorizado.urls', namespace='motorizado')),
    url(r'^pedidos/', include('pedido.urls', namespace='pedido')),
    url(r'^reporte/', include('reporte.urls', namespace='reporte')),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^$', login_required(views.Index.as_view()), name='index'),
]
# + static(setting2.STATIC_URL, document_root=setting2.STATIC_ROOT) + static(setting2.MEDIA_URL, document_root=setting2.MEDIA_ROOT)

motorizado/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
import views
from django.contrib.auth.decorators import login_required


# Gestion de motorizado
urlpatterns = [
    url(r'^motorizado/add/$', views.add_motorizado, name='add_motorizado'),
    url(r'^motorizado/search/$', views.searchMotorizado, name='search_motorizado'),
    url(r'^motorizado/list/$', login_required(TemplateView.as_view(
        template_name='motorizado/motorizado.html')), name='list_motorizado'),
    url(r'^motorizado/edit/(?P<motorizado_id>\d+)/$',
        views.editMotorizado, name='edit_motorizado'),
    url(r'^moto/details/(?P<moto_id>\d+)/$',
        views.infoMoto, name='api_info_moto'),
    url(r'^motorizado/search/pedido/$', login_required(views.SearchMotorizadoPed.as_view()), name='search_pedido_motorizado'),
]

# Gestion de despacho
urlpatterns += [
    url(r'^rastreo/$', login_required(views.Rastreo.as_view()), name='rastreo_motorizado'),
]

# Gestion de Moto
urlpatterns += [
    url(r'^moto/$', login_required(TemplateView.as_view(template_name='motorizado/index.html')),
        name="index_moto"),
    url(r'^moto/add/$', login_required(views.MotoAdd.as_view()), name='add_moto'),
    url(r'^moto/list/$', login_required(TemplateView.as_view(template_name='motorizado/motoSearch.html')), name='list_moto'),
    url(r'^moto/search/$', views.ListMoto, name='search_moto'),
    url(r'^moto/delete/(?P<pk>\d+)/$', views.DeleteMoto, name='delete_moto'),
    url(r'^moto/edit/(?P<pk>\d+)/$', login_required(views.EditMoto.as_view()), name='edit_moto'),
    url(r'^moto/asignar/$', login_required(views.AsignarMoto.as_view()), name='asignar_moto'),

]

# Gestion de Foto += [
urlpatterns += [
    url(r'^motorizado/foto/$', login_required(TemplateView.as_view(template_name='motorizado/foto.html')),
        name='foto_pedido_motorizado'),
    url(r'^text/$', login_required(TemplateView.as_view(template_name='motorizado/text.html')),
        name='text'),
]

# Gestion de Rastreo pedido
urlpatterns += [
    url(r'^ws/list/rastreo/$', login_required(views.ListarRastreo.as_view()), name='listar_rastreo'),

]


# Gestion cantidad de periodos en el periodo actual de quincena
urlpatterns += [
    url(r'^get/info/$', views.InfoMotorizado.as_view(), name='info_motorizado'),
]


# Gestion cantidad de periodos en el periodo actual de quincena
urlpatterns += [
    url(r'^get/pedidos/$', login_required(views.CantidadPedido.as_view()), name='num_pedidos'),

]

# Gestion listar motorizado
urlpatterns += [
    url(r'^ws/list/motorizado/$', views.ListMotorizado.as_view(), name='ws_list_moto'),
]

# Gestion listar motorizado
urlpatterns += [
    url(r'^notificaciones/$', views.ListNotificaciones.as_view(), name='ws_list_noti'),
    url(r'^ws/notificaciones/$', views.ValidListNotificaciones.as_view(), name='ws_valid_list_noti'),
    url(r'^ws/valid/tecsoap/$', views.ValidSoatTecno.as_view(), name='ws_valid_tecno_soap'),
]

pedido/urls.py
from django.conf.urls import patterns, url
from . import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


# Gestion de pedido
urlpatterns = [
    url(r'^pedido/$', login_required(TemplateView.as_view(template_name='pedido/index.html')), name='index_pedido'),
    url(r'^pedido/admin/add/$', login_required(views.AddPedidoAdmin.as_view()), name='add_admin_pedido'),
    url(r'^pedido/edit/(?P<pk>\d+)/$', login_required(views.EditPedido.as_view()), name='edit_pedido'),
    url(r'^pedido/info/(?P<pk>\d+)/$', login_required(views.InfoPedido.as_view()), name='info_pedido'),
    url(r'^pedido/factura/(?P<pk>\d+)/$', login_required(views.FacturaPedido.as_view(template_name='pedido/factura.html')), name='factura_pedido'),
    url(r'^pedido/list/$', login_required(TemplateView.as_view(template_name='pedido/pedidosSearch.html')), name='list_pedido'),
    url(r'^pedido/search/$', login_required(views.TablaPedido.as_view()), name='search_pedido'),
    url(r'^pedido/mis/$', login_required(views.MisPedidos.as_view()), name='mis_pedido'),
    url(r'^pedido/mis/pedidos/$', login_required(views.TablaMisPedidos.as_view()), name='pedidos_pedido'),
]

# Gestion de despacho
urlpatterns += [
    url(r'^despacho/$', login_required(views.Despacho.as_view()), name='despachar_pedido'),
    url(r'^pedido/despacho/search/$', login_required(views.TablaDespachoPedido.as_view()), name='despachar_search_pedido'),
    url(r'^pedido/despacho/update/$', login_required(views.UpdateServicePedido.as_view()), name='despachar_update_pedido'),
    url(r'^pedido/entrega/update/$', login_required(views.UpdateEntregaServicePedido.as_view()), name='entrega_update_pedido'),
]

# Gestion de Item
urlpatterns += [
    url(r'^pedido/add/item/(?P<pk>\d+)/$', login_required(views.AddItemPedido.as_view()), name='add_item_pedido'),
    url(r'^pedido/finalizar/(?P<pk>\d+)/$', login_required(views.FinalizarPedido.as_view()), name='final_item_pedido'),
    url(r'^item/add/$', login_required(views.AddItem.as_view()), name='add_item'),
    url(r'^item/edit/(?P<pk>\d+)/$', login_required(views.UpdateItem.as_view()), name='edit_item'),
    url(r'^item/list/$', login_required(TemplateView.as_view(template_name='pedido/itemsSearch.html')), name='list_item'),
    url(r'^item/search/$', login_required(views.TablaItems.as_view()), name='search_item'),
    url(r'^item/delete/(?P<pk>\d+)/(?P<id_pedido>\d+)/$', login_required(views.DeleteItemPedido.as_view()), name='delete_item_pedido'),
]

# Gestion Asignacion Motorizado a Pedido
urlpatterns += [
    url(r'^asignar/motorizado/$', login_required(views.AsignarMotorizado.as_view()), name='asignar_motorizado_pedido'),
    url(r'^asignar/motorizado/search/$', login_required(views.TablaPedidosAsignar.as_view()), name='tabla_asignar_motorizado_pedido'),
    url(r'^asignar/motorizado/pedido/(?P<pedido_id>\d+)/$', login_required(views.AsignarPedidoMotorizado.as_view()), name='motorizado_asignar_pedido'),
    url(r'^asignar/motorizado/close/(?P<pedido_id>\d+)/$', login_required(views.CAMotorizado.as_view()), name='motorizado_cerrar_asignar_pedido'),

]

# Getsion de actualizacion de pedidos
urlpatterns += [
    url(r'^motorizado/up/ser/pedido/$', login_required(views.UpSerPedido.as_view()), name='mot_up_serPedido'),
    url(r'^motorizado/up/ser/entrega/$', login_required(views.UpdPedSerEntrega.as_view()), name='up_ser_entrega_pedido'),
]


# Getsion de actualizacion de pedidos
urlpatterns += [
    url(r'^emp/ws/pedido/$', views.WsPedidoEmpresa.as_view(), name='ws_serPedido'),
]


# Gestion de Ws
urlpatterns += [
    url(r'^rastreo/$', login_required(views.Rastreo.as_view()), name='rastreo'),
    url(r'^res/ws/pedido/$', login_required(views.UpSerPedido.as_view()), name='up_serPedido'),
]


# Gestion de recepcion de pedido
urlpatterns += [
    url(r'^aceptar/pws/$', views.AceptarPWService.as_view(), name='aceptar_pwservice'),
    url(r'^aceptar/pplataforma/$', views.AceptarPPlataforma.as_view(), name='aceptar_pplataforma'),
]


# Gestion de recoger de pedido
urlpatterns += [
    url(r'^recoger/pplataforma/$', views.RecogerPPlataforma.as_view(), name='recoger_pplataforma'),
    url(r'^recoger/pws/$', views.RecogerPWService.as_view(), name='recoger_wservice'),
]


# Gestion de entrega de pedido
urlpatterns += [
    url(r'^entregar/pplataforma/$', views.EntregarPPlataforma.as_view(), name='entregar_pplataforma'),
    url(r'^entregar/pws/$', views.EntregarPWService.as_view(), name='entregar_wservice'),
]


# Gestion de entrega de pedido
urlpatterns += [
    url(r'^confirmar/pplataforma/$', views.ConfirmacionPedido.as_view(), name='confirmar_pplataforma'),
    url(r'^confirmar/pws/$', views.ConfirmacionPedidoWS.as_view(), name='confirmar_wservice'),
]


# Gestion de cancelar de pedido
urlpatterns += [
    url(r'^cancelar/pplataforma/$', views.CancelarPPlataforma.as_view(), name='cancelar_pplataforma'),
    url(r'^cancelar/pws/$', views.CancelarPWService.as_view(), name='cancelar_wservice'),
]


# Gestion de reactivar de pedido
urlpatterns += [
    url(r'^reactivar/pplataforma/$', views.ReactivarPPlataforma.as_view(), name='reactivar_pplataforma'),
]


# Gestion de Configuracion de tiempos
urlpatterns += [
    url(r'^configuracion/$', views.ConfiguracionTiempo.as_view(), name='configurar_pplataforma'),
]


# Gestion Auto Asignar Pedido
urlpatterns += [
    url(r'^autoasignar/$', views.AutoAsignar.as_view(), name='autoasignar'),
]

# Gestion Auto Asignar Pedido
urlpatterns += [
    url(r'^ws/cancelado/$', views.WsPedidoCancelado.as_view(), name='wspedidocanceladofinal'),
    url(r'^ws/reactivar/$', views.WsPedidoReactivar.as_view(), name='wspedidoreactivar'),
]

# Gestion de Consulta de pedido
urlpatterns += [
    url(r'^info/pedido/cliente/$', TemplateView.as_view(template_name='pedido/pedidoinfo.html'), name='info_pedido_cliente'),
    url(r'^ws/info/pedido/$', views.WsInfoPedido.as_view(), name='ws_info_pedido'),
]

# Gestion de pedidos cancelados
urlpatterns += [
    url(r'^cancelados/$', login_required(TemplateView.as_view(template_name='pedido/cancelados.html')), name='pedidos_cancelados'),
    url(r'^ws/cancelados/$', views.TablaCancelados.as_view(), name='ws_pedidos_cancelados'),
    url(r'^ws/motivos/cancelacion/$', views.MotCancelacion.as_view(), name='ws_motv_cancelados'),    
]

#Servicios para consummir desde el mobil
urlpatterns += [
    url(r'^ws/mobil/list/pedidos/$',views.ListPedidosMotorizadoMobil.as_view(), name='mobil_list_pedidos'),
    url(r'^ws/get/pedido/$',views.GetPedidoMotorizadoMobil.as_view(), name='mobil_get_pedido'),
]

usuario/urls.py
from django.conf.urls import patterns, url
import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'login/$', views.custom_login, {'template_name': 'usuario/login.html'}, name='user-login'),
    url(r'logout/$', views.custom_logout, {'next_page': '/', }, name='user-logout'),
]


urlpatterns += [
    url(r'session/$', views.Login.as_view(), name='user-login2'),
    url(r'empleado/$', login_required(TemplateView.as_view(template_name='usuario/index.html')), name='index'),
    url(r'empleado/add/$', login_required(views.EmpleadoAdd.as_view()), name='add_empleado'),
    url(r'empleado/update/states/(?P<empleado_id>\d+)/$', login_required(views.UpStaCliente.as_view()), name='upd_state_empleado'),
    url(r'^empleado/list/$', login_required(TemplateView.as_view(template_name='usuario/empleadoSearch.html')), name='list_empleado'),
    url(r'^empleado/search/$', login_required(views.searchEmpleadoTabla), name='seach_empleado'),
    url(r'^empleado/details/(?P<empleado_id>\d+)/$', views.infoEmpleado, name='details_empleado'),
    url(r'^empleado/edit/(?P<empleado_id>\d+)/$', views.editEmpleado, name='edit_empleado'),
    url(r'^empleado/edit/pass/(?P<pk>\d+)/$', login_required(views.PassChangeEmpleado.as_view(template_name='usuario/passChangeEmpleado.html')), name='edit_pass_empleado'),
    url(r'^$', login_required(views.Index.as_view()), name='index_general'),
]

urlpatterns += [
    url(r'^empresa/list/$', views.EmpresaListView.as_view(), name='empresa_list'),
]


# Gestion de Clientes
urlpatterns += [
    url(r'^cliente/$', login_required(views.IndexCliente.as_view()), name='index_cliente'),
    url(r'^cliente/add/$', login_required(views.ClienteAdd.as_view()), name='add_cliente'),
    url(r'^cliente/list/$', login_required(TemplateView.as_view(template_name='usuario/clienteSearch.html')), name='list_cliente'),
    url(r'^cliente/search/$', views.searchCliente, name='search_cliente'),
    url(r'^cliente/details/(?P<pk>\d+)/$', login_required(views.DetailCliente.as_view(template_name='usuario/infoCliente.html')), name='details_cliente'),
    url(r'^cliente/edit/(?P<pk>\d+)/$', login_required(views.UpdateCliente.as_view(template_name='usuario/editCliente.html')), name='edit_cliente'),
]

# Gestion de Tienda
urlpatterns += [
    url(r'^tienda/$', login_required(views.IndexTienda.as_view()), name='index_tienda'),
    url(r'^tienda/add/$', login_required(views.AddTienda.as_view()), name='add_tienda'),
    url(r'^tienda/edit/(?P<pk>\d+)/$', login_required(views.UpdateTienda.as_view()), name='update_tienda'),
    url(r'^tienda/details/(?P<pk>\d+)/$', login_required(views.DetailTienda.as_view()), name='details_tienda'),
    url(r'^tienda/delete/(?P<pk>\d+)/$', login_required(views.DeleteTienda.as_view()), name='delete_tienda'),
    url(r'^tienda/list/$', login_required(views.ListTienda.as_view()), name='list_tienda'),
    url(r'^tienda/list/search/$', login_required(views.TablaTienda.as_view()), name='search_tienda'),
]


# Gestion servicios de autenticacion
urlpatterns += [
    url(r'tiendas/ws/', login_required(views.Store.as_view()), name='get_tiendas'),
]


# Gestion servicios de autenticacion
urlpatterns += [
    url(r'session/', views.Login.as_view(), name='ws_loguin'),
    url(r'logged/', views.is_logged, name="is_logged"),
    url(r'set/password/$', views.SetPassWord.as_view(), name="set_password"),
]

# Gestion listar motorizado
urlpatterns += [
    url(r'^ws/list/supervisor/$', login_required(views.ListSupervisor.as_view()), name='ws_list_super'),
    url(r'^ws/list/alistador/$', login_required(views.ListAlistador.as_view()), name='ws_list_alist'),
]

#Solicitud de accesso a la plataform
urlpatterns += [
    url(r'^ws/solicitud/acceso/$', views.SolicitudAccesoView.as_view(), name='ws_solicitar_acceso'),
]

motorizado/models.py
import re
from django.db import models
from usuario.models import Empleado, Empresa
from django.core import validators


class Soat(models.Model):
    numeroS = models.CharField(max_length=50, unique=True, validators=[validators.RegexValidator(re.compile('^[0-9]+$'), ('numero no valida'), 'invalid')])
    fecha_expedicionS = models.DateField()
    fecha_expiracionS = models.DateField()

    def __str__(self):
        return self.numeroS

    class Meta:
        verbose_name = "Soat"
        verbose_name_plural = "Soats"
    # end class


class Tecno(models.Model):
    numeroT = models.CharField(max_length=50, unique=True, validators=[
                               validators.RegexValidator(re.compile('^[0-9]+$'), ('numero no valida'), 'invalid')])
    fecha_expedicionT = models.DateField()
    fecha_expiracionT = models.DateField()

    def __str__(self):
        return self.numeroT
    # end def

    class Meta:
        verbose_name = "Tecnomecanica"
        verbose_name_plural = "Tecnomecanicas"
    # end class

TIPO_MOTORIZADO = ((1, 'Planta'), (2, 'Suscrito'))


class Moto(models.Model):
    tipo = models.CharField(max_length=50)
    marca = models.CharField(max_length=50)
    placa = models.CharField(max_length=6, unique=True)
    empresaM = models.ForeignKey(Empresa)
    soat = models.OneToOneField(Soat)
    tecno = models.OneToOneField(Tecno)
    t_propiedad = models.CharField(
        ("Tarjeta de Propiedad"), max_length=50, unique=True)
    estado = models.BooleanField(default=True)

    def __str__(self):
        return self.placa
    # end def

    class Meta:
        verbose_name = "Moto"
        verbose_name_plural = "Motos"
# end class


class Motorizado(models.Model):
    empleado = models.OneToOneField(Empleado)
    tipo = models.IntegerField(choices=TIPO_MOTORIZADO)
    licencia = models.CharField(max_length=50, unique=True, validators=[validators.RegexValidator(re.compile('^[0-9]+$'), ('licencia no valida'), 'invalid')])
    identifier = models.CharField(max_length=20, blank=True, null=True)
    moto = models.OneToOneField(Moto)

    class Meta:
        verbose_name = "Motorizado"
        verbose_name_plural = "Motorizados"
    # end if

    def __str__(self):
        return str(self.empleado)
    # end if

    def __unicode__(self):
        return self.empleado.first_name
    # end if


class Configuracion(models.Model):
    empresa = models.ForeignKey(Empresa)
    soat = models.IntegerField()
    soat = models.IntegerField()

    def __str__(self):
        return self.empresa.first_name
    # end def

    def __unicode__(self):
        return self.empresa.first_name
    # end def
# end class

motorizado/templates/motorizado/addMoto.html
{% extends "exp/base_user.html" %}
{% load staticfiles %}
{% block title %}Añadir Moto{% endblock %}
{% block addcss_user %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/flora.datepick.css' %}">
{% endblock %}
{% block content_user %}
<div class="one column row">
	<div class="column">
		<div class="ui labeled huge input">
      <a href="{% url 'motorizado:index_moto' %}" class="ui teal icon huge button">
        <i class="express-atras icon"></i>
      </a>
      <a class="ui olive label">Nueva Moto</a>
    </div>
	</div>
	{% if mensaje %}
  <div class="ui center aligned container row">
    <div class="ui {{ mensaje.tipo }} message">
      <div class=" content">
        <div class="header">
          {{ mensaje.texto }}
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</div>
<div class="ui container grid" style="margin-bottom:50px;">
  <div class="center aligned column">
		<form method="POST" action="{% url 'motorizado:add_moto' %}" class="ui form">
			{% csrf_token %}
			<h2 class="ui teal header">Descripción General</h2>
	    <div class="four fields">
				<div class="field {% if formMoto.tipo.errors %}error{% endif %}">
					{{ formMoto.tipo }}
				</div>
				<div class="field {% if formMoto.marca.errors %}error{% endif %}">
					{{ formMoto.marca }}
				</div>
				<div class="field {% if formMoto.placa.errors %}error{% endif %}">
					{{ formMoto.placa }}
				</div>
				<div class="field {% if formMoto.t_propiedad.errors %}error{% endif %}">
					{{ formMoto.t_propiedad }}
				</div>
	    </div>
			<div class="ui stackable two column grid">
			  <div class="column">
					<h2 class="ui teal header">Técnico-mecánica</h2>
					<div class="field {% if formTecno.numeroT.errors %}error{% endif %}">
			      {{ formTecno.numeroT }}
			    </div>
					<div class="two fields">
						<div class="field {% if formTecno.fecha_expedicionT.errors %}error{% endif %}">
							{{ formTecno.fecha_expedicionT }}
						</div>
						<div class="field {% if formTecno.fecha_expiracionT.errors %}error{% endif %}">
							{{ formTecno.fecha_expiracionT }}
						</div>
					</div>
			  </div>
			  <div class="column">
					<h2 class="ui teal header">Soat</h2>
					<div class="field {% if formSoat.numeroS.errors %}error{% endif %}">
			      {{ formSoat.numeroS }}
			    </div>
					<div class="two fields">
						<div class="field {% if formSoat.fecha_expedicionS.errors %}error{% endif %}">
							{{ formSoat.fecha_expedicionS }}
						</div>
						<div class="field {% if formSoat.fecha_expiracionS.errors %}error{% endif %}">
							{{ formSoat.fecha_expiracionS }}
						</div>
					</div>
			  </div>
			</div>

			<button type="submit" class="ui olive fluid large button">Registrar</button>

		</form>
  </div>
</div>
{% endblock %}

{% block addjs %}
<script type="text/javascript" src="{% static 'js/jquery.plugin.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.datepick.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.datepick-es.js' %}"></script>
<script type="text/javascript" src="{% static 'js/browser.js' %}"></script>
<script type="text/javascript">
	$(document).ready(function(){
		var b = new Browser();
		if(b.name != "chrome"){
			$('#id_fecha_expedicionT').datepick();
			$('#id_fecha_expiracionT').datepick();
			$('#id_fecha_expedicionS').datepick();
			$('#id_fecha_expiracionS').datepick();
		}
	});
</script>
{% endblock %}

motorizado/templates/motorizado/addMotorizado.html
{% extends "exp/base_user.html" %}
{% block title %}Añadir Moto{% endblock %}
{% block addcss_user %}
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/flora.datepick.css">
{% endblock %}
{% block content_user %}
<div class="one column row">
	<div class="column">
		<div class="ui labeled huge input">
      <a href="{% url 'usuario:index' %}" class="ui teal icon huge button">
        <i class="express-atras icon"></i>
      </a>
      <a class="ui olive label">Nuevo Motorizado</a>
    </div>
	</div>
	{% if mensaje %}
  		<div class="ui center aligned container row">
    		<div class="ui {{ mensaje.tipo }} message">
    			<div class=" content">
        			<div class="header">
          				{{ mensaje.texto }}
        			</div>
		        </div>
    		</div>
  		</div>
  	{% endif %}
</div>
<div class="ui container grid" style="margin-bottom:50px;">
  <div class="center aligned column">
		{% if error %}
			<div class="ui center aligned container row">
    			<div class="ui negative message">
    				<div class=" content">
        				<div class="header">
          					{{ error}}
        				</div>
		        	</div>
    			</div>
  			</div>
		{% else %}
		<form method="POST" action="{% url 'motorizado:add_motorizado' %}" class="ui form">
			{% csrf_token %}
			<h2 class="ui teal header">&nbsp;</h2>
	    <div class="four fields">
				<div class="field {% if formMotorizado.empleado.errors %}error{% endif %}">
					{{ formMotorizado.empleado}}
				</div>
				<div class="field {% if formMotorizado.licencia.errors %}error{% endif %}">
					{{ formMotorizado.licencia }}
				</div>
				<div class="field {% if formMotorizado.identifier.errors %}error{% endif %}">
					{{ formMotorizado.identifier }}
				</div>
	    </div>
			<h2 class="ui teal header">Descripción General</h2>
	    <div class="four fields">
				<div class="field {% if formMoto.tipo.errors %}error{% endif %}">
					{{ formMoto.tipo }}
				</div>
				<div class="field {% if formMoto.marca.errors %}error{% endif %}">
					{{ formMoto.marca }}
				</div>
				<div class="field {% if formMoto.placa.errors %}error{% endif %}">
					{{ formMoto.placa }}
				</div>
				<div class="field {% if formMoto.t_propiedad.errors %}error{% endif %}">
					{{ formMoto.t_propiedad }}
				</div>
	    </div>
			<div class="ui stackable two column grid">
			  <div class="column">
					<h2 class="ui teal header">Tecnomecanica</h2>
					<div class="field {% if formTecno.numeroT.errors %}error{% endif %}">
			      {{ formTecno.numeroT }}
			    </div>
					<div class="two fields">
						<div class="field {% if formTecno.fecha_expedicionT.errors %}error{% endif %}">
							{{ formTecno.fecha_expedicionT }}
						</div>
						<div class="field {% if formTecno.fecha_expiracionT.errors %}error{% endif %}">
							{{ formTecno.fecha_expiracionT }}
						</div>
					</div>
			  </div>
			  <div class="column">
					<h2 class="ui teal header">Soat</h2>
					<div class="field {% if formSoat.numeroS.errors %}error{% endif %}">
			      {{ formSoat.numeroS }}
			    </div>
					<div class="two fields">
						<div class="field {% if formSoat.fecha_expedicionS.errors %}error{% endif %}">
							{{ formSoat.fecha_expedicionS }}
						</div>
						<div class="field {% if formSoat.fecha_expiracionS.errors %}error{% endif %}">
							{{ formSoat.fecha_expiracionS }}
						</div>
					</div>
			  </div>
			</div>

			<button type="submit" class="ui olive fluid large button">Registrar</button>

		</form>
		{% endif %}
  </div>
</div>
{% endblock %}

{% block addjs %}
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.plugin.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.datepick.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.datepick-es.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/browser.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
		var b = new Browser();
		if (b.name != "chrome"){
			$('#id_fecha_expedicionT').datepick();
			$('#id_fecha_expiracionT').datepick();
			$('#id_fecha_expedicionS').datepick();
			$('#id_fecha_expiracionS').datepick();
		}
		var Empleado = document.getElementById('id_empleado');
		Empleado.options[0].innerHTML = "Empleado";
		$('.ui.dropdown').dropdown();
	});
</script>
{% endblock %}

motorizado/templates/motorizado/foto2.html
<!DOCTYPE html>
<html lang='en'>
<head>
  <meta charset='utf-8' />
  <title>Using getUserMedia with HTML5 <video> and <canvas></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <style>
    body {
      margin-top:2%;
      text-align:center;
      color:#fff;
      background-color:#122836;
    }
    video { 
      position:absolute;
      visibility:hidden;
    }
    canvas { border:8px solid #fff;}
    button {
      border:none;
      display:block;
      padding:0.5em 1em;
      margin:1% auto 0;
      cursor:pointer;
      color:#fff;
      background-color:#9f361b;
    }
    button:active { background-color:#e44d26; }
  </style>
  <script src='https://software.intel.com/sites/landingpage/html5hub/webcam-access.js'></script>
</head>
<body>
  <h1>Using getUserMedia with HTML5 &lt;video&gt; and &lt;canvas&gt;</h1>
  <video id='v'></video>  
  <canvas id='c'></canvas>
  <button id='grey'>Toggle Greyness</button>
</body>
</html>