exp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import views
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
import settings

urlpatterns = [
    url(r'^plataforma/', include(admin.site.urls)),
    url(r'^usuario/', include('usuario.urls', namespace='usuario')),
    url(r'^motorizado/', include('motorizado.urls', namespace='motorizado')),
    url(r'^pedidos/', include('pedido.urls', namespace='pedido')),
    url(r'^reporte/', include('reporte.urls', namespace='reporte')),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^$', login_required(views.Index.as_view()), name='index'),
]
# + static(setting2.STATIC_URL, document_root=setting2.STATIC_ROOT) + static(setting2.MEDIA_URL, document_root=setting2.MEDIA_ROOT)

motorizado/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
import views
from django.contrib.auth.decorators import login_required


# Gestion de motorizado
urlpatterns = [
    url(r'^motorizado/add/$', views.add_motorizado, name='add_motorizado'),
    url(r'^motorizado/search/$', views.searchMotorizado, name='search_motorizado'),
    url(r'^motorizado/list/$', login_required(TemplateView.as_view(
        template_name='motorizado/motorizado.html')), name='list_motorizado'),
    url(r'^motorizado/edit/(?P<motorizado_id>\d+)/$',
        views.editMotorizado, name='edit_motorizado'),
    url(r'^moto/details/(?P<moto_id>\d+)/$',
        views.infoMoto, name='api_info_moto'),
    url(r'^motorizado/search/pedido/$', login_required(views.SearchMotorizadoPed.as_view()), name='search_pedido_motorizado'),
]

# Gestion de despacho
urlpatterns += [
    url(r'^rastreo/$', login_required(views.Rastreo.as_view()), name='rastreo_motorizado'),
]

# Gestion de Moto
urlpatterns += [
    url(r'^moto/$', login_required(TemplateView.as_view(template_name='motorizado/index.html')),
        name="index_moto"),
    url(r'^moto/add/$', login_required(views.MotoAdd.as_view()), name='add_moto'),
    url(r'^moto/list/$', login_required(TemplateView.as_view(template_name='motorizado/motoSearch.html')), name='list_moto'),
    url(r'^moto/search/$', views.ListMoto, name='search_moto'),
    url(r'^moto/delete/(?P<pk>\d+)/$', views.DeleteMoto, name='delete_moto'),
    url(r'^moto/edit/(?P<pk>\d+)/$', login_required(views.EditMoto.as_view()), name='edit_moto'),
    url(r'^moto/asignar/$', login_required(views.AsignarMoto.as_view()), name='asignar_moto'),

]

# Gestion de Foto += [
urlpatterns += [
    url(r'^motorizado/foto/$', login_required(TemplateView.as_view(template_name='motorizado/foto.html')),
        name='foto_pedido_motorizado'),
    url(r'^text/$', login_required(TemplateView.as_view(template_name='motorizado/text.html')),
        name='text'),
]

# Gestion de Rastreo pedido
urlpatterns += [
    url(r'^ws/list/rastreo/$', login_required(views.ListarRastreo.as_view()), name='listar_rastreo'),

]


# Gestion cantidad de periodos en el periodo actual de quincena
urlpatterns += [
    url(r'^get/info/$', views.InfoMotorizado.as_view(), name='info_motorizado'),
]


# Gestion cantidad de periodos en el periodo actual de quincena
urlpatterns += [
    url(r'^get/pedidos/$', login_required(views.CantidadPedido.as_view()), name='num_pedidos'),

]

# Gestion listar motorizado
urlpatterns += [
    url(r'^ws/list/motorizado/$', views.ListMotorizado.as_view(), name='ws_list_moto'),
]

# Gestion listar motorizado
urlpatterns += [
    url(r'^notificaciones/$', views.ListNotificaciones.as_view(), name='ws_list_noti'),
    url(r'^ws/notificaciones/$', views.ValidListNotificaciones.as_view(), name='ws_valid_list_noti'),
    url(r'^ws/valid/tecsoap/$', views.ValidSoatTecno.as_view(), name='ws_valid_tecno_soap'),
]

pedido/urls.py
from django.conf.urls import patterns, url
from . import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


# Gestion de pedido
urlpatterns = [
    url(r'^pedido/$', login_required(TemplateView.as_view(template_name='pedido/index.html')), name='index_pedido'),
    url(r'^pedido/admin/add/$', login_required(views.AddPedidoAdmin.as_view()), name='add_admin_pedido'),
    url(r'^pedido/edit/(?P<pk>\d+)/$', login_required(views.EditPedido.as_view()), name='edit_pedido'),
    url(r'^pedido/info/(?P<pk>\d+)/$', login_required(views.InfoPedido.as_view()), name='info_pedido'),
    url(r'^pedido/factura/(?P<pk>\d+)/$', login_required(views.FacturaPedido.as_view(template_name='pedido/factura.html')), name='factura_pedido'),
    url(r'^pedido/list/$', login_required(TemplateView.as_view(template_name='pedido/pedidosSearch.html')), name='list_pedido'),
    url(r'^pedido/search/$', login_required(views.TablaPedido.as_view()), name='search_pedido'),
    url(r'^pedido/mis/$', login_required(views.MisPedidos.as_view()), name='mis_pedido'),
    url(r'^pedido/mis/pedidos/$', login_required(views.TablaMisPedidos.as_view()), name='pedidos_pedido'),
]

# Gestion de despacho
urlpatterns += [
    url(r'^despacho/$', login_required(views.Despacho.as_view()), name='despachar_pedido'),
    url(r'^pedido/despacho/search/$', login_required(views.TablaDespachoPedido.as_view()), name='despachar_search_pedido'),
    url(r'^pedido/despacho/update/$', login_required(views.UpdateServicePedido.as_view()), name='despachar_update_pedido'),
    url(r'^pedido/entrega/update/$', login_required(views.UpdateEntregaServicePedido.as_view()), name='entrega_update_pedido'),
]

# Gestion de Item
urlpatterns += [
    url(r'^pedido/add/item/(?P<pk>\d+)/$', login_required(views.AddItemPedido.as_view()), name='add_item_pedido'),
    url(r'^pedido/finalizar/(?P<pk>\d+)/$', login_required(views.FinalizarPedido.as_view()), name='final_item_pedido'),
    url(r'^item/add/$', login_required(views.AddItem.as_view()), name='add_item'),
    url(r'^item/edit/(?P<pk>\d+)/$', login_required(views.UpdateItem.as_view()), name='edit_item'),
    url(r'^item/list/$', login_required(TemplateView.as_view(template_name='pedido/itemsSearch.html')), name='list_item'),
    url(r'^item/search/$', login_required(views.TablaItems.as_view()), name='search_item'),
    url(r'^item/delete/(?P<pk>\d+)/(?P<id_pedido>\d+)/$', login_required(views.DeleteItemPedido.as_view()), name='delete_item_pedido'),
]

# Gestion Asignacion Motorizado a Pedido
urlpatterns += [
    url(r'^asignar/motorizado/$', login_required(views.AsignarMotorizado.as_view()), name='asignar_motorizado_pedido'),
    url(r'^asignar/motorizado/search/$', login_required(views.TablaPedidosAsignar.as_view()), name='tabla_asignar_motorizado_pedido'),
    url(r'^asignar/motorizado/pedido/(?P<pedido_id>\d+)/$', login_required(views.AsignarPedidoMotorizado.as_view()), name='motorizado_asignar_pedido'),
    url(r'^asignar/motorizado/close/(?P<pedido_id>\d+)/$', login_required(views.CAMotorizado.as_view()), name='motorizado_cerrar_asignar_pedido'),

]

# Getsion de actualizacion de pedidos
urlpatterns += [
    url(r'^motorizado/up/ser/pedido/$', login_required(views.UpSerPedido.as_view()), name='mot_up_serPedido'),
    url(r'^motorizado/up/ser/entrega/$', login_required(views.UpdPedSerEntrega.as_view()), name='up_ser_entrega_pedido'),
]


# Getsion de actualizacion de pedidos
urlpatterns += [
    url(r'^emp/ws/pedido/$', views.WsPedidoEmpresa.as_view(), name='ws_serPedido'),
]


# Gestion de Ws
urlpatterns += [
    url(r'^rastreo/$', login_required(views.Rastreo.as_view()), name='rastreo'),
    url(r'^res/ws/pedido/$', login_required(views.UpSerPedido.as_view()), name='up_serPedido'),
]


# Gestion de recepcion de pedido
urlpatterns += [
    url(r'^aceptar/pws/$', views.AceptarPWService.as_view(), name='aceptar_pwservice'),
    url(r'^aceptar/pplataforma/$', views.AceptarPPlataforma.as_view(), name='aceptar_pplataforma'),
]


# Gestion de recoger de pedido
urlpatterns += [
    url(r'^recoger/pplataforma/$', views.RecogerPPlataforma.as_view(), name='recoger_pplataforma'),
    url(r'^recoger/pws/$', views.RecogerPWService.as_view(), name='recoger_wservice'),
]


# Gestion de entrega de pedido
urlpatterns += [
    url(r'^entregar/pplataforma/$', views.EntregarPPlataforma.as_view(), name='entregar_pplataforma'),
    url(r'^entregar/pws/$', views.EntregarPWService.as_view(), name='entregar_wservice'),
]


# Gestion de entrega de pedido
urlpatterns += [
    url(r'^confirmar/pplataforma/$', views.ConfirmacionPedido.as_view(), name='confirmar_pplataforma'),
    url(r'^confirmar/pws/$', views.ConfirmacionPedidoWS.as_view(), name='confirmar_wservice'),
]


# Gestion de cancelar de pedido
urlpatterns += [
    url(r'^cancelar/pplataforma/$', views.CancelarPPlataforma.as_view(), name='cancelar_pplataforma'),
    url(r'^cancelar/pws/$', views.CancelarPWService.as_view(), name='cancelar_wservice'),
]


# Gestion de reactivar de pedido
urlpatterns += [
    url(r'^reactivar/pplataforma/$', views.ReactivarPPlataforma.as_view(), name='reactivar_pplataforma'),
]


# Gestion de Configuracion de tiempos
urlpatterns += [
    url(r'^configuracion/$', views.ConfiguracionTiempo.as_view(), name='configurar_pplataforma'),
]


# Gestion Auto Asignar Pedido
urlpatterns += [
    url(r'^autoasignar/$', views.AutoAsignar.as_view(), name='autoasignar'),
]

# Gestion Auto Asignar Pedido
urlpatterns += [
    url(r'^ws/cancelado/$', views.WsPedidoCancelado.as_view(), name='wspedidocanceladofinal'),
    url(r'^ws/reactivar/$', views.WsPedidoReactivar.as_view(), name='wspedidoreactivar'),
]

# Gestion de Consulta de pedido
urlpatterns += [
    url(r'^info/pedido/cliente/$', TemplateView.as_view(template_name='pedido/pedidoinfo.html'), name='info_pedido_cliente'),
    url(r'^ws/info/pedido/$', views.WsInfoPedido.as_view(), name='ws_info_pedido'),
]

# Gestion de pedidos cancelados
urlpatterns += [
    url(r'^cancelados/$', login_required(TemplateView.as_view(template_name='pedido/cancelados.html')), name='pedidos_cancelados'),
    url(r'^ws/cancelados/$', views.TablaCancelados.as_view(), name='ws_pedidos_cancelados'),
    url(r'^ws/motivos/cancelacion/$', views.MotCancelacion.as_view(), name='ws_motv_cancelados'),    
]

#Servicios para consummir desde el mobil
urlpatterns += [
    url(r'^ws/mobil/list/pedidos/$',views.ListPedidosMotorizadoMobil.as_view(), name='mobil_list_pedidos'),
    url(r'^ws/get/pedido/$',views.GetPedidoMotorizadoMobil.as_view(), name='mobil_get_pedido'),
]

reporte/urls.py
from django.conf.urls import patterns, url
import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

# pedidos entregados en la empresa
urlpatterns = [
    url(r'^reporte/$', login_required(TemplateView.as_view(template_name='reporte/index.html')), name='index_reporte'),
    url(r'^pedidos/$', login_required(TemplateView.as_view(template_name='reporte/pedidos.html')), name='pedidos_reporte'),
    url(r'^pedidos/search/$', login_required(views.Pedido.as_view()), name='search_pedidos_reporte'),
]

# pedidos en los que interactua los empleados
urlpatterns += [
    url(r'^empleados/$', login_required(views.Empleados.as_view()), name='empleados_reporte'),
    url(r'^load/empleados/$', login_required(TemplateView.as_view(template_name='reporte/tablaempleado.html')), name='ajax_empleados_reporte'),
    url(r'^tabla/empleados/$', login_required(views.TablaEmpleado.as_view()), name='tabla_empleados_reporte'),
]

# Generacion de informes de empleados
urlpatterns += [
    url(r'^tiempos/empleados/$', login_required(views.TiempoEmpleado.as_view()), name='tiempos_empleado_reporte'),
    url(r'^tabla/info/empleados/$', login_required(views.TablaInfoEmpleado.as_view()), name='info_tabla_empleados_reporte'),
    url(r'^excel/$', login_required(views.Excel.as_view()), name='excel_reporte'),
    url(r'^pdf/$', login_required(views.Pdf.as_view()), name='pdf_reporte'),
]

usuario/urls.py
from django.conf.urls import patterns, url
import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'login/$', views.custom_login, {'template_name': 'usuario/login.html'}, name='user-login'),
    url(r'logout/$', views.custom_logout, {'next_page': '/', }, name='user-logout'),
]


urlpatterns += [
    url(r'session/$', views.Login.as_view(), name='user-login2'),
    url(r'empleado/$', login_required(TemplateView.as_view(template_name='usuario/index.html')), name='index'),
    url(r'empleado/add/$', login_required(views.EmpleadoAdd.as_view()), name='add_empleado'),
    url(r'empleado/update/states/(?P<empleado_id>\d+)/$', login_required(views.UpStaCliente.as_view()), name='upd_state_empleado'),
    url(r'^empleado/list/$', login_required(TemplateView.as_view(template_name='usuario/empleadoSearch.html')), name='list_empleado'),
    url(r'^empleado/search/$', login_required(views.searchEmpleadoTabla), name='seach_empleado'),
    url(r'^empleado/details/(?P<empleado_id>\d+)/$', views.infoEmpleado, name='details_empleado'),
    url(r'^empleado/edit/(?P<empleado_id>\d+)/$', views.editEmpleado, name='edit_empleado'),
    url(r'^empleado/edit/pass/(?P<pk>\d+)/$', login_required(views.PassChangeEmpleado.as_view(template_name='usuario/passChangeEmpleado.html')), name='edit_pass_empleado'),
    url(r'^$', login_required(views.Index.as_view()), name='index_general'),
]

urlpatterns += [
    url(r'^empresa/list/$', views.EmpresaListView.as_view(), name='empresa_list'),
]


# Gestion de Clientes
urlpatterns += [
    url(r'^cliente/$', login_required(views.IndexCliente.as_view()), name='index_cliente'),
    url(r'^cliente/add/$', login_required(views.ClienteAdd.as_view()), name='add_cliente'),
    url(r'^cliente/list/$', login_required(TemplateView.as_view(template_name='usuario/clienteSearch.html')), name='list_cliente'),
    url(r'^cliente/search/$', views.searchCliente, name='search_cliente'),
    url(r'^cliente/details/(?P<pk>\d+)/$', login_required(views.DetailCliente.as_view(template_name='usuario/infoCliente.html')), name='details_cliente'),
    url(r'^cliente/edit/(?P<pk>\d+)/$', login_required(views.UpdateCliente.as_view(template_name='usuario/editCliente.html')), name='edit_cliente'),
]

# Gestion de Tienda
urlpatterns += [
    url(r'^tienda/$', login_required(views.IndexTienda.as_view()), name='index_tienda'),
    url(r'^tienda/add/$', login_required(views.AddTienda.as_view()), name='add_tienda'),
    url(r'^tienda/edit/(?P<pk>\d+)/$', login_required(views.UpdateTienda.as_view()), name='update_tienda'),
    url(r'^tienda/details/(?P<pk>\d+)/$', login_required(views.DetailTienda.as_view()), name='details_tienda'),
    url(r'^tienda/delete/(?P<pk>\d+)/$', login_required(views.DeleteTienda.as_view()), name='delete_tienda'),
    url(r'^tienda/list/$', login_required(views.ListTienda.as_view()), name='list_tienda'),
    url(r'^tienda/list/search/$', login_required(views.TablaTienda.as_view()), name='search_tienda'),
]


# Gestion servicios de autenticacion
urlpatterns += [
    url(r'tiendas/ws/', login_required(views.Store.as_view()), name='get_tiendas'),
]


# Gestion servicios de autenticacion
urlpatterns += [
    url(r'session/', views.Login.as_view(), name='ws_loguin'),
    url(r'logged/', views.is_logged, name="is_logged"),
    url(r'set/password/$', views.SetPassWord.as_view(), name="set_password"),
]

# Gestion listar motorizado
urlpatterns += [
    url(r'^ws/list/supervisor/$', login_required(views.ListSupervisor.as_view()), name='ws_list_super'),
    url(r'^ws/list/alistador/$', login_required(views.ListAlistador.as_view()), name='ws_list_alist'),
]

#Solicitud de accesso a la plataform
urlpatterns += [
    url(r'^ws/solicitud/acceso/$', views.SolicitudAccesoView.as_view(), name='ws_solicitar_acceso'),
]

usuario/templates/usuario/addCliente.html
{% extends "exp/base_user.html" %}
{% block title %}Añadir Cliente{% endblock %}
{% block content_user %}
<div class="one column row">
	<div class="column">
		<div class="ui labeled huge input">
			<a href="{% url 'usuario:index_cliente' %}" class="ui teal icon huge button">
				<i class="express-atras icon"></i>
			</a>
			<a class="ui olive label">Nuevo Cliente</a>
		</div>
	</div>
	<div class="column">
		{% if mensaje %}
			<div class="ui center aligned container row">
				<div class="ui {{ mensaje.tipo }} message">
					<div class=" content">
						<div class="header">
							{{ mensaje.texto }}
						</div>
					</div>
				</div>
			</div>
		{% endif %}
	</div>
</div>
<div class="ui container grid" style="margin-bottom:50px;">
  <div class="center aligned column">
		<form method="POST" action="{% url 'usuario:add_cliente' %}" class="ui form">
			{% csrf_token %}
			<h2 class="ui teal header">Información Personal</h2>
	    <div class="four fields">
	      <div class="field {% if form.first_name.errors %}error{% endif %}">
	        {{ form.first_name }}
	      </div>
	      <div class="field {% if form.last_name.errors %}error{% endif %}">
	        {{ form.last_name }}
	      </div>
				<div class="field {% if form.tipo_id.errors %}error{% endif %}">
					{{ form.tipo_id }}
				</div>
				<div class="field {% if form.identificacion.errors %}error{% endif %}">
					{{ form.identificacion }}
				</div>
	    </div>

			<h2 class="ui teal header">Información de Contacto</h2>
	    <div class="three fields">
	      <div class="field {% if form.telefono_celular.errors %}error{% endif %}">
	        {{ form.telefono_celular }}
	      </div>
	      <div class="field {% if form.telefono_fijo.errors %}error{% endif %}">
	        {{ form.telefono_fijo }}
	      </div>
				<div class="field {% if form.direccion.errors %}error{% endif %}">
					{{ form.direccion }}
				</div>
	    </div>

	    <div class="three fields">
				<div class="field {% if form.barrio.errors %}error{% endif %}">
					{{ form.barrio }}
				</div>
				<div class="field {% if form.ciudad.errors %}error{% endif %}">
					{{ form.ciudad }}
				</div>
	      <div class="field {% if form.zona.errors %}error{% endif %}">
	        {{ form.zona }}
	      </div>
	    </div>
			<button type="submit" class="ui olive fluid large button">Registrar</button>

		</form>
  </div>
</div>
{% endblock %}

{% block addjs %}
<script type="text/javascript">
$( document ).ready(function() {
	$('.ui.dropdown').dropdown();
});
</script>
{% endblock %}

usuario/templates/usuario/clienteSearch.html
{% extends "exp/base_user.html" %}
{% load staticfiles %}
{% block title %}Buscar Clientes{% endblock %}
{% block content_user %}
<div class="one column row">
	<div class="column">
		<div class="ui labeled huge input">
      <a href="{% url 'usuario:index_cliente' %}" class="ui teal icon huge button">
        <i class="express-atras icon"></i>
      </a>
      <a class="ui olive label">Listar Clientes</a>
    </div>
	</div>
	<div class="column">
		{% if mensaje %}
			<div class="ui center aligned container row">
				<div class="ui {{ mensaje.tipo }} message">
					<div class=" content">
						<div class="header">
							{{ mensaje.texto }}
						</div>
					</div>
				</div>
			</div>
		{% endif %}
	</div>
</div>
<div class="ui container grid" style="margin-bottom:50px;">
  <div class="center aligned column">
		<div class="column row">
			<div class="column">
				{% csrf_token %}
				Presiona Enter en el campo de busqueda para ver todos los Clientes
					<div class="ui icon fluid input">
					<input type="text" name="search" id="search" autofocus placeholder="Buscar por Apellidos/Identificación">
					<i class="search icon"></i>
				</div>
			</div>
		</div>
		<h4 class="ui horizontal divider header">
			<i class="express-listar icon"></i>
			Resultados
		</h4>
		<div class="column row">
			<div class="column">
				<table id="search-results" class="ui very basic striped unstackable table">
					<thead>
			        	<tr>
			        		<th>Nombre</th>
			        		<th>Apellidos</th>
			        		<th>Identificacion</th>
			        		<th></th>
			        	</tr>
			        </thead>
			        <tbody>

			        </tbody>
				</table>
			</div>
		</div>
  </div>
</div>
{% endblock %}

{% block addjs %}
	<script src="{% static 'api/js/jquery.js' %}"></script>
	<script src="{% static 'api/js/jquery.min.js' %}"></script>
	<script src="{% static 'api/js/dataTables.js' %}"></script>
	<script src="{% static 'api/js/tabla_ajax_cliente.js' %}"></script>
	<script src="{% static 'api/js/clienteSearch.js' %}""></script>
{% endblock %}

usuario/templates/usuario/index_general.html
{% extends "exp/base_user.html" %}
{% load staticfiles %}
{% block title %}Inicio {{ request.session.empresa }}{% endblock %}
{% block addcss_user %}<link rel="stylesheet" type="text/css" href="{% static 'css/style_index.css' %}">{% endblock %}
{% block content_user %}
  <div class="one middle aligned column row">
    <div class="center aligned  column">
      {% if request.session.cargo == 'ADMINISTRADOR' or request.session.cargo == 'SUPERVISOR'%}
      <div class="ui vertical compact labeled icon inverted huge teal menu">
        <a href="{% url 'usuario:index_cliente' %}" class="item">
          <h3><i class="material-icons huge">perm_identity</i></h3>
          Clientes
        </a>
      </div>
      {% endif %}
      {% if request.session.cargo == 'ADMINISTRADOR' or request.session.cargo == 'SUPERVISOR'%}
      <div class="ui vertical compact labeled icon inverted huge teal menu">
        <a href="{% url 'usuario:index_tienda' %}" class="item">
          <h3><i class="material-icons huge">store</i></h3>
          Tiendas
        </a>
      </div>
      {% endif %}
      {% if request.session.cargo == 'ADMINISTRADOR' or request.session.cargo == 'SUPERVISOR'%}
      <div class="ui vertical compact labeled icon inverted teal huge menu">
        <a href="{% url 'motorizado:index_moto' %}"class="item">
          <h3><i class="material-icons huge">motorcycle</i></h3>
          Motos
        </a>
      </div>
      {% endif %}
      {% if request.session.cargo == 'ADMINISTRADOR' %}
      <div class="ui vertical compact labeled icon inverted teal huge menu">
        <a href="{% url 'usuario:index' %}" class="item">
          <h3><i class="material-icons huge">work</i></h3>
          Empleados
        </a>
      </div>
      {% endif %}
      {% if request.session.cargo == 'SUPERVISOR' or request.session.cargo == 'ADMINISTRADOR' %}
      <div class="ui vertical compact labeled icon inverted teal huge menu">
        <a href="{% url 'pedido:index_pedido' %}" class="item">
          <h3><i class="material-icons huge">shopping_cart</i></h3>
          Pedidos
        </a>
      </div>
      {% endif %}
      {% if request.session.cargo == 'ALISTADOR' or request.session.cargo == 'MOTORIZADO'  %}
      <div class="ui vertical compact labeled icon inverted teal huge menu">
      <a href="{% url 'pedido:mis_pedido' %}"class="item">
        <h3><i class="material-icons huge">shopping_cart</i></h3>
        Mis Pedidos
      </a>
    </div>
      {% endif %}
      {% if request.session.cargo == 'ALISTADOR' %}
      <div class="ui vertical compact labeled icon inverted teal huge menu">
        <a href="{% url 'pedido:asignar_motorizado_pedido' %}" class="item">
          <h3><i class="material-icons huge">add_shopping_cart</i></h3>
          Asignar Pedidos
        </a>
      </div>
      {% endif %}
      {% if request.session.cargo == 'SUPERVISOR' or request.session.cargo == 'ADMINISTRADOR' %}
        <div class="ui vertical compact labeled icon inverted teal huge menu">
          <a href="{% url 'motorizado:rastreo_motorizado' %}" class="item">
            <h3><i class="material-icons huge">map</i></h3>
            Rastreo
          </a>
        </div>
      {% endif %}
      {% if request.session.cargo == 'SUPERVISOR' or request.session.cargo == 'ADMINISTRADOR' %}
        <div class="ui vertical compact labeled icon inverted teal huge menu">
          <a href="{% url 'reporte:index_reporte' %}" class="item">
            <h3><i class="material-icons huge">insert_drive_file</i></h3>
            Reporte
          </a>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

usuario/templates/usuario/index_tienda.html
{% extends "exp/base_user.html" %}
{% load staticfiles %}
{% block title %}Clientes{% endblock %}
{% block addcss_user %}<link rel="stylesheet" type="text/css" href="{% static 'css/style_index.css' %}">{% endblock %}
{% block content_user %}
<style type="text/css"></style>
<div class="one column row">
  <div class="column">
    <div class="ui labeled huge input">
      <a href="{% url 'usuario:index_general' %}" class="ui teal icon huge button">
        <i class="express-atras icon"></i>
      </a>
      <a class="ui olive label">Tiendas</a>
    </div>
  </div>
    {% if mensaje %}
  <div class="ui center aligned container column">
  <div class="ui {{ mensaje.tipo }} message">
    <div class=" content">
    <div class="header">
      {{ mensaje.texto }}
    </div>
    </div>
  </div>
  </div>
  {% endif %}
</div>
<div class="one column row">
  <div class="center aligned column">
    <div class="ui vertical compact labeled icon inverted huge teal menu">
      <a href="{% url 'usuario:add_tienda' %}" class="item">
        <h3><i class="material-icons huge">store_mall_directory</i></h3>
        Nueva Tienda
      </a>
    </div>
    <div class="ui vertical compact labeled icon inverted teal huge menu">
      <a href="{% url 'usuario:list_tienda' %}" class="item">
        <h3><i class="material-icons huge">list</i></h3>
        Listar Tienda
      </a>
    </div>
  </div>
</div>
{% endblock %}

usuario/templates/usuario/set_password.html
<form id="form" method="post">
  {% csrf_token %}
  <ul>
      {{ form.as_ul }}
  </ul>
  <input type="submit" value="OK">
</form>

usuario/templates/usuario/solicitud_acceso.html
<form action="" method="post">{% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Send message" />
</form>