exp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import views
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
import settings

urlpatterns = [
    url(r'^plataforma/', include(admin.site.urls)),
    url(r'^usuario/', include('usuario.urls', namespace='usuario')),
    url(r'^motorizado/', include('motorizado.urls', namespace='motorizado')),
    url(r'^pedidos/', include('pedido.urls', namespace='pedido')),
    url(r'^reporte/', include('reporte.urls', namespace='reporte')),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^$', login_required(views.Index.as_view()), name='index'),
]
# + static(setting2.STATIC_URL, document_root=setting2.STATIC_ROOT) + static(setting2.MEDIA_URL, document_root=setting2.MEDIA_ROOT)

pedido/urls.py
from django.conf.urls import patterns, url
from . import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


# Gestion de pedido
urlpatterns = [
    url(r'^pedido/$', login_required(TemplateView.as_view(template_name='pedido/index.html')), name='index_pedido'),
    url(r'^pedido/admin/add/$', login_required(views.AddPedidoAdmin.as_view()), name='add_admin_pedido'),
    url(r'^pedido/edit/(?P<pk>\d+)/$', login_required(views.EditPedido.as_view()), name='edit_pedido'),
    url(r'^pedido/info/(?P<pk>\d+)/$', login_required(views.InfoPedido.as_view()), name='info_pedido'),
    url(r'^pedido/factura/(?P<pk>\d+)/$', login_required(views.FacturaPedido.as_view(template_name='pedido/factura.html')), name='factura_pedido'),
    url(r'^pedido/list/$', login_required(TemplateView.as_view(template_name='pedido/pedidosSearch.html')), name='list_pedido'),
    url(r'^pedido/search/$', login_required(views.TablaPedido.as_view()), name='search_pedido'),
    url(r'^pedido/mis/$', login_required(views.MisPedidos.as_view()), name='mis_pedido'),
    url(r'^pedido/mis/pedidos/$', login_required(views.TablaMisPedidos.as_view()), name='pedidos_pedido'),
]

# Gestion de despacho
urlpatterns += [
    url(r'^despacho/$', login_required(views.Despacho.as_view()), name='despachar_pedido'),
    url(r'^pedido/despacho/search/$', login_required(views.TablaDespachoPedido.as_view()), name='despachar_search_pedido'),
    url(r'^pedido/despacho/update/$', login_required(views.UpdateServicePedido.as_view()), name='despachar_update_pedido'),
    url(r'^pedido/entrega/update/$', login_required(views.UpdateEntregaServicePedido.as_view()), name='entrega_update_pedido'),
]

# Gestion de Item
urlpatterns += [
    url(r'^pedido/add/item/(?P<pk>\d+)/$', login_required(views.AddItemPedido.as_view()), name='add_item_pedido'),
    url(r'^pedido/finalizar/(?P<pk>\d+)/$', login_required(views.FinalizarPedido.as_view()), name='final_item_pedido'),
    url(r'^item/add/$', login_required(views.AddItem.as_view()), name='add_item'),
    url(r'^item/edit/(?P<pk>\d+)/$', login_required(views.UpdateItem.as_view()), name='edit_item'),
    url(r'^item/list/$', login_required(TemplateView.as_view(template_name='pedido/itemsSearch.html')), name='list_item'),
    url(r'^item/search/$', login_required(views.TablaItems.as_view()), name='search_item'),
    url(r'^item/delete/(?P<pk>\d+)/(?P<id_pedido>\d+)/$', login_required(views.DeleteItemPedido.as_view()), name='delete_item_pedido'),
]

# Gestion Asignacion Motorizado a Pedido
urlpatterns += [
    url(r'^asignar/motorizado/$', login_required(views.AsignarMotorizado.as_view()), name='asignar_motorizado_pedido'),
    url(r'^asignar/motorizado/search/$', login_required(views.TablaPedidosAsignar.as_view()), name='tabla_asignar_motorizado_pedido'),
    url(r'^asignar/motorizado/pedido/(?P<pedido_id>\d+)/$', login_required(views.AsignarPedidoMotorizado.as_view()), name='motorizado_asignar_pedido'),
    url(r'^asignar/motorizado/close/(?P<pedido_id>\d+)/$', login_required(views.CAMotorizado.as_view()), name='motorizado_cerrar_asignar_pedido'),

]

# Getsion de actualizacion de pedidos
urlpatterns += [
    url(r'^motorizado/up/ser/pedido/$', login_required(views.UpSerPedido.as_view()), name='mot_up_serPedido'),
    url(r'^motorizado/up/ser/entrega/$', login_required(views.UpdPedSerEntrega.as_view()), name='up_ser_entrega_pedido'),
]


# Getsion de actualizacion de pedidos
urlpatterns += [
    url(r'^emp/ws/pedido/$', views.WsPedidoEmpresa.as_view(), name='ws_serPedido'),
]


# Gestion de Ws
urlpatterns += [
    url(r'^rastreo/$', login_required(views.Rastreo.as_view()), name='rastreo'),
    url(r'^res/ws/pedido/$', login_required(views.UpSerPedido.as_view()), name='up_serPedido'),
]


# Gestion de recepcion de pedido
urlpatterns += [
    url(r'^aceptar/pws/$', views.AceptarPWService.as_view(), name='aceptar_pwservice'),
    url(r'^aceptar/pplataforma/$', views.AceptarPPlataforma.as_view(), name='aceptar_pplataforma'),
]


# Gestion de recoger de pedido
urlpatterns += [
    url(r'^recoger/pplataforma/$', views.RecogerPPlataforma.as_view(), name='recoger_pplataforma'),
    url(r'^recoger/pws/$', views.RecogerPWService.as_view(), name='recoger_wservice'),
]


# Gestion de entrega de pedido
urlpatterns += [
    url(r'^entregar/pplataforma/$', views.EntregarPPlataforma.as_view(), name='entregar_pplataforma'),
    url(r'^entregar/pws/$', views.EntregarPWService.as_view(), name='entregar_wservice'),
]


# Gestion de entrega de pedido
urlpatterns += [
    url(r'^confirmar/pplataforma/$', views.ConfirmacionPedido.as_view(), name='confirmar_pplataforma'),
    url(r'^confirmar/pws/$', views.ConfirmacionPedidoWS.as_view(), name='confirmar_wservice'),
]


# Gestion de cancelar de pedido
urlpatterns += [
    url(r'^cancelar/pplataforma/$', views.CancelarPPlataforma.as_view(), name='cancelar_pplataforma'),
    url(r'^cancelar/pws/$', views.CancelarPWService.as_view(), name='cancelar_wservice'),
]


# Gestion de reactivar de pedido
urlpatterns += [
    url(r'^reactivar/pplataforma/$', views.ReactivarPPlataforma.as_view(), name='reactivar_pplataforma'),
]


# Gestion de Configuracion de tiempos
urlpatterns += [
    url(r'^configuracion/$', views.ConfiguracionTiempo.as_view(), name='configurar_pplataforma'),
]


# Gestion Auto Asignar Pedido
urlpatterns += [
    url(r'^autoasignar/$', views.AutoAsignar.as_view(), name='autoasignar'),
]

# Gestion Auto Asignar Pedido
urlpatterns += [
    url(r'^ws/cancelado/$', views.WsPedidoCancelado.as_view(), name='wspedidocanceladofinal'),
    url(r'^ws/reactivar/$', views.WsPedidoReactivar.as_view(), name='wspedidoreactivar'),
]

# Gestion de Consulta de pedido
urlpatterns += [
    url(r'^info/pedido/cliente/$', TemplateView.as_view(template_name='pedido/pedidoinfo.html'), name='info_pedido_cliente'),
    url(r'^ws/info/pedido/$', views.WsInfoPedido.as_view(), name='ws_info_pedido'),
]

# Gestion de pedidos cancelados
urlpatterns += [
    url(r'^cancelados/$', login_required(TemplateView.as_view(template_name='pedido/cancelados.html')), name='pedidos_cancelados'),
    url(r'^ws/cancelados/$', views.TablaCancelados.as_view(), name='ws_pedidos_cancelados'),
    url(r'^ws/motivos/cancelacion/$', views.MotCancelacion.as_view(), name='ws_motv_cancelados'),    
]

#Servicios para consummir desde el mobil
urlpatterns += [
    url(r'^ws/mobil/list/pedidos/$',views.ListPedidosMotorizadoMobil.as_view(), name='mobil_list_pedidos'),
    url(r'^ws/get/pedido/$',views.GetPedidoMotorizadoMobil.as_view(), name='mobil_get_pedido'),
]

usuario/urls.py
from django.conf.urls import patterns, url
import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'login/$', views.custom_login, {'template_name': 'usuario/login.html'}, name='user-login'),
    url(r'logout/$', views.custom_logout, {'next_page': '/', }, name='user-logout'),
]


urlpatterns += [
    url(r'session/$', views.Login.as_view(), name='user-login2'),
    url(r'empleado/$', login_required(TemplateView.as_view(template_name='usuario/index.html')), name='index'),
    url(r'empleado/add/$', login_required(views.EmpleadoAdd.as_view()), name='add_empleado'),
    url(r'empleado/update/states/(?P<empleado_id>\d+)/$', login_required(views.UpStaCliente.as_view()), name='upd_state_empleado'),
    url(r'^empleado/list/$', login_required(TemplateView.as_view(template_name='usuario/empleadoSearch.html')), name='list_empleado'),
    url(r'^empleado/search/$', login_required(views.searchEmpleadoTabla), name='seach_empleado'),
    url(r'^empleado/details/(?P<empleado_id>\d+)/$', views.infoEmpleado, name='details_empleado'),
    url(r'^empleado/edit/(?P<empleado_id>\d+)/$', views.editEmpleado, name='edit_empleado'),
    url(r'^empleado/edit/pass/(?P<pk>\d+)/$', login_required(views.PassChangeEmpleado.as_view(template_name='usuario/passChangeEmpleado.html')), name='edit_pass_empleado'),
    url(r'^$', login_required(views.Index.as_view()), name='index_general'),
]

urlpatterns += [
    url(r'^empresa/list/$', views.EmpresaListView.as_view(), name='empresa_list'),
]


# Gestion de Clientes
urlpatterns += [
    url(r'^cliente/$', login_required(views.IndexCliente.as_view()), name='index_cliente'),
    url(r'^cliente/add/$', login_required(views.ClienteAdd.as_view()), name='add_cliente'),
    url(r'^cliente/list/$', login_required(TemplateView.as_view(template_name='usuario/clienteSearch.html')), name='list_cliente'),
    url(r'^cliente/search/$', views.searchCliente, name='search_cliente'),
    url(r'^cliente/details/(?P<pk>\d+)/$', login_required(views.DetailCliente.as_view(template_name='usuario/infoCliente.html')), name='details_cliente'),
    url(r'^cliente/edit/(?P<pk>\d+)/$', login_required(views.UpdateCliente.as_view(template_name='usuario/editCliente.html')), name='edit_cliente'),
]

# Gestion de Tienda
urlpatterns += [
    url(r'^tienda/$', login_required(views.IndexTienda.as_view()), name='index_tienda'),
    url(r'^tienda/add/$', login_required(views.AddTienda.as_view()), name='add_tienda'),
    url(r'^tienda/edit/(?P<pk>\d+)/$', login_required(views.UpdateTienda.as_view()), name='update_tienda'),
    url(r'^tienda/details/(?P<pk>\d+)/$', login_required(views.DetailTienda.as_view()), name='details_tienda'),
    url(r'^tienda/delete/(?P<pk>\d+)/$', login_required(views.DeleteTienda.as_view()), name='delete_tienda'),
    url(r'^tienda/list/$', login_required(views.ListTienda.as_view()), name='list_tienda'),
    url(r'^tienda/list/search/$', login_required(views.TablaTienda.as_view()), name='search_tienda'),
]


# Gestion servicios de autenticacion
urlpatterns += [
    url(r'tiendas/ws/', login_required(views.Store.as_view()), name='get_tiendas'),
]


# Gestion servicios de autenticacion
urlpatterns += [
    url(r'session/', views.Login.as_view(), name='ws_loguin'),
    url(r'logged/', views.is_logged, name="is_logged"),
    url(r'set/password/$', views.SetPassWord.as_view(), name="set_password"),
]

# Gestion listar motorizado
urlpatterns += [
    url(r'^ws/list/supervisor/$', login_required(views.ListSupervisor.as_view()), name='ws_list_super'),
    url(r'^ws/list/alistador/$', login_required(views.ListAlistador.as_view()), name='ws_list_alist'),
]

#Solicitud de accesso a la plataform
urlpatterns += [
    url(r'^ws/solicitud/acceso/$', views.SolicitudAccesoView.as_view(), name='ws_solicitar_acceso'),
]

pedido/templates/pedido/addConfiguracion.html
{% extends "exp/base_user.html" %} {% block title %}Añadir Pedido{% endblock %} {% block content_user %}
<div class="one column row">
	<div class="column">
		<div class="ui labeled huge input">
			<a href="{% url 'pedido:index_pedido' %}" class="ui teal icon huge button">
				<i class="express-atras icon"></i>
			</a>
			<a class="ui olive label">Configuracion Gestion de Pedido</a>
		</div>
	</div>
	{% if mensaje %}
	<div class="ui center aligned container column">
		<div class="ui {{ mensaje.tipo }} message">
			<div class=" content">
				<div class="header">
					{{ mensaje.texto }}
				</div>
			</div>
		</div>
	</div>
	{% endif %}
</div>
<div class="ui container grid" style="margin-bottom:50px;">
	<div class="center aligned column">
		<form method="POST" action="{% url 'pedido:configurar_pplataforma' %}" class="ui form">
			<input type="hidden" name="id" value="{{ pk }}"
			{% csrf_token %}
			<h2 class="ui teal header">&nbsp;</h2>
			<div class="three fields">
				<div class="field {% if form.retraso.errors %}error{% endif %}">
					{{ form.retraso }}
				</div>
				<div class="field {% if form.pedido.errors %}error{% endif %}">
					{{ form.pedido }}
				</div>
				<div class="field {% if form.gps.errors %}error{% endif %}">
					{{ form.gps }}
				</div>
			</div>

			<div class="three fields">
				<div class="field {% if form.distancia.errors %}error{% endif %}">
					{{ form.distancia }}
				</div>
				<div class="field {% if form.primero.errors %}error{% endif %}">
					{{ form.primero }}
				</div>
				<div class="field {% if form.segundo.errors %}error{% endif %}">
					{{ form.segundo }}
				</div>
			</div>
			<button type="submit" class="ui olive fluid large button">Registrar</button>
		</form>
	</div>
</div>

{% endblock %} {% block addjs %}
<script>
	$(document).ready(function() {
		$('.ui.dropdown').dropdown();
	});
	$(function() {
		$('#add-cliente').click(function() {
			$('#cliente-form').modal('show');
		});
	});
</script>
{% endblock %}

pedido/templates/pedido/addItems.html
{% extends "exp/base_user.html" %}
{% block title %}Nuevo Item{% endblock %}
{% block content_user %}
<div class="one column row">
  <div class="column">
    <div class="ui labeled huge input">
      <a href="{% url 'pedido:index_pedido' %}" class="ui teal icon huge button">
      <i class="express-atras icon"></i>
      </a>
      <a class="ui olive label">Nuevo Item</a>
    </div>
  </div>
  {% if mensaje %}
      <div class="ui center aligned container row">
        <div class="ui {{ mensaje.tipo }} message">
          <div class=" content">
            <div class="header">
              {{ mensaje.texto }}
            </div>
          </div>
        </div>
      </div>
   {% endif %}
</div>

<div class="ui container grid" style="margin-bottom:50px;">
  <div class="center aligned column">
    <div class="column row">
      <div class="column">
        <h2 class="ui olive header">Item</h2>
        <form method="POST" class="ui form">
          {% csrf_token %}

          <div class="two fields">
            <div class="field {% if form.codigo.errors %}error{% endif %}">
              {{form.codigo}}
            </div>
            <div class="field {% if form.presentacion.errors %}error{% endif %}">
              {{ form.presentacion }}
            </div>
          </div>
          <h2 class="ui header"></h2>
          <div class="field {% if form.descripcion.errors %}error{% endif %}">
            {{ form.descripcion }}
          </div>
          <h2 class="ui header"></h2>
          <button type="submit" class="ui olive fluid large button">Añadir</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block addjs %}
<script>
  $( document ).ready(function() {
    $('.ui.dropdown').dropdown();
  });
</script>
{% endblock %}

pedido/templates/pedido/chooseMotorizado.html
{% extends "exp/base_user.html" %}
{% load staticfiles %}
{% block title %}Ecoga un Motorizado{% endblock %}
{% block content_user %}
<div class="one column row">
	<div class="column">
		<div class="ui labeled huge input">
			<a href="{% url 'pedido:asignar_motorizado_pedido' %}" class="ui teal icon huge button">
			<i class="express-atras icon"></i>
			</a>
			<a class="ui olive label">Asignar Motorizado al pedido {{pedido}}</a>
		</div>
	</div>
</div>

<div class="ui container grid" style="margin-bottom:50px;">
  <div class="center aligned column">
		<div class="column row">
			<div class="column">
				<h2 class="ui olive header">Motorizados a Asignar</h2>
				<form method="POST" action="{% url 'pedido:motorizado_cerrar_asignar_pedido' pedido %}"  class="ui form">
					{% csrf_token %}
					<input type="hidden" name="pedido" value="{{pedido}}" required>
					<div class="two fields">
						<div class="field {% if form.item.errors %}error{% endif %}">
							<select class="ui search dropdown" required name="motorizado">
								<option value="">Motorizado</option>
								{% for motorizado in motorizados %}
								<option value="{{ motorizado.empleado.identificacion }}">{{ motorizado.empleado.first_name|title }} {{ motorizado.empleado.last_name|title }} {{motorizado.empleado.empresa.first_name}}</option>
								{% endfor %}
								{% for motorizadoE in motorizadosE %}
								<option value="{{ motorizadoE.empleado.identificacion }}">{{ motorizadoE.empleado.first_name|title }} {{ motorizadoE.empleado.last_name|title }} {{motorizadoE.empleado.empresa.first_name}}</option>
								{% endfor %}
							</select>
						</div>
						<div class="field">
							<button type="submit" class="ui blue fluid  button">Asignar</button>
			      </div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block addjs %}
<script>
	$( document ).ready(function() {
		$('.ui.dropdown').dropdown();
	});
</script>
{% endblock %}

pedido/templates/pedido/index.html
{% extends "exp/base_user.html" %}
{% load staticfiles %}
{% block title %}Pedidos{% endblock %}
{% block addcss_user %}<link rel="stylesheet" type="text/css" href="{% static 'css/style_index.css' %}">{% endblock %}
{% block content_user %}
<style type="text/css"></style>
<div class="one column row">
  <div class="column">
    <div class="ui labeled huge input">
      <a href="{% url 'usuario:index_general' %}" class="ui teal icon huge button">
        <i class="express-atras icon"></i>
      </a>
      <a class="ui olive label">Pedidos</a>
    </div>
  </div>
</div>
<div class="one column row">
  <div class="center aligned column">
    {% if request.session.cargo == 'ADMINISTRADOR' or request.session.cargo == 'SUPERVISOR' %}
    <div class="ui vertical compact labeled icon inverted huge teal menu">
      <a href="{% url 'pedido:add_admin_pedido' %}" class="item">
        <h3><i class="material-icons huge">add_shopping_cart</i></h3>
        Nuevo Pedido
      </a>
    </div>
    {% endif %}
    {% if request.session.cargo == 'ADMINISTRADOR' or request.session.cargo == 'SUPERVISOR' %}
    <div class="ui vertical compact labeled icon inverted teal huge menu">
      <a href="{% url 'pedido:list_pedido' %}"class="item">
        <h3><i class="material-icons huge">list</i></h3>
        Listado Pedidos
      </a>
    </div>
    {% endif %}
    {% if request.session.cargo == 'ADMINISTRADOR' %}
    <div class="ui vertical compact labeled icon inverted teal huge menu">
      <a href="{% url 'pedido:add_item' %}"class="item">
        <h3><i class="material-icons huge">layers</i></h3>
        Nuevos Items
      </a>
    </div>
    {% endif %}
    {% if request.session.cargo == 'ADMINISTRADOR' or request.session.cargo == 'SUPERVISOR' %}
    <div class="ui vertical compact labeled icon inverted teal huge menu">
      <a href="{% url 'pedido:pedidos_cancelados' %}"class="item">
        <h3><i class="material-icons huge">list</i></h3>
        Pedidos Cancelados
      </a>
    </div>
    {% endif %}
    {% if request.session.cargo == 'ADMINISTRADOR' or request.session.cargo == 'SUPERVISOR' %}
    <div class="ui vertical compact labeled icon inverted teal huge menu">
      <a href="{% url 'pedido:list_item' %}"class="item">
        <h3><i class="material-icons huge">list</i></h3>
        Listado Items
      </a>
    </div>
    {% endif %}
    {% if request.session.cargo == 'ADMINISTRADOR' or request.session.cargo == 'SUPERVISOR' %}
    <div class="ui vertical compact labeled icon inverted huge teal menu">
      <a href="{% url 'pedido:despachar_pedido' %}" class="item">
        <h3><i class="material-icons huge">shopping_cart</i></h3>
        Despachar
      </a>
    </div>
    {% endif %}
    <div class="ui vertical compact labeled icon inverted teal huge menu">
      <a href="{% url 'pedido:mis_pedido' %}"class="item">
        <h3><i class="material-icons huge">shopping_cart</i></h3>
        Mis Pedidos
      </a>
    </div>
    {% if request.session.cargo == 'SUPERVISOR' or request.session.cargo == 'ADMINISTRADOR' %}
      <div class="ui vertical compact labeled icon inverted teal huge menu">
        <a href="{% url 'pedido:configurar_pplataforma' %}" class="item">
          <h3><i class="material-icons huge">settings</i></h3>
          Configuracion
        </a>
      </div>
    {% endif %}
  </div>
</div>
{% endblock %}

pedido/templates/pedido/misPedidos.html
{% extends "exp/base_user.html" %}
{% load staticfiles %}
{% block title %}Mis Pedidos{% endblock %}
{% block content_user %}
<div class="one column row">
	<div class="column">
		<div class="ui labeled huge input">
      {% if request.session.cargo == 'ALISTADOR' or request.session.cargo == 'MOTORIZADO' %}
      <a href="{% url 'usuario:index_general' %}" class="ui teal icon huge button">
        <i class="express-atras icon"></i>
      </a>
      {% else %}
      <a href="{% url 'pedido:index_pedido' %}" class="ui teal icon huge button">
        <i class="express-atras icon"></i>
      </a>
      {% endif %}
      <a class="ui olive label">Mis Pedidos</a>
    </div>
	</div>
</div>
<div class="ui container grid" style="margin-bottom:50px;">
  <div class="center aligned column">
		<div class="column row">
			<div class="column">
				<table id="search-results" class="ui very basic striped unstackable table">
						<thead>
								<tr>
									<th>Codigo</th>
									<th>Numero Express</th>
									<th>Fecha</th>
									<th>Mas Información</th>
								</tr>
						</thead>
						{% for pedido in pedidos %}
						<tr>
							<td>{{ pedido.num_pedido }}</td>
							<td>{{ pedido.npedido_express }}</td>
							<td>{{ pedido.fecha_pedido }}</td>
							<td><a href="{% url 'domicilios:api_info_pedido' pedido.id %}" class="ui icon green"><i class="unhide large green icon"></i></a></td>
						</tr>
						{% endfor %}
				</table>
			</div>
		</div>
  </div>
</div>
{% endblock %}
{% block addjs %}
	<script src="{% static 'api/js/jquery.js' %}"></script>
	<script src="{% static 'api/js/jquery.min.js' %}"></script>
	<script src="{% static 'api/js/dataTables.js' %}"></script>
	<script type="text/javascript" src="{% static 'api/js/tabla_ajax_mis_pedidos.js' %}"></script>
{% endblock %}

pedido/templates/pedido/pedidoItems.html
{% extends "exp/base_user.html" %}
{% block title %}Añadir Items{% endblock %}
{% block content_user %}
{% load humanize %}
<div class="one column row">
	<div class="column">
		<div class="ui labeled huge input">
		  <a class="ui olive label">Realizar Pedido</a>
		</div>
	</div>
	{% if mensaje %}
  <div class="ui center aligned container column">
	<div class="ui warning message">
	  <div class=" content">
		<div class="header">
		  {{ error }}
		</div>
	  </div>
	</div>
  </div>
  {% endif %}
</div>

<div class="ui container grid" style="margin-bottom:50px;">
  <div class="center aligned column">
		<div class="column row">
			<div class="column">
				<h2 class="ui olive header">Item</h2>
				<form method="POST" action="{% url 'pedido:add_item_pedido' pedido.id %}" class="ui form">
					{% csrf_token %}
					<div class="four fields">
						<div class="field {% if form.item.errors %}error{% endif %} ui action input">
							{{form.item}}
							<a href="{% url 'pedido:add_item' %}" class="ui blue icon button"><i class="plus icon"></i></a>
						</div>
						<div class="field {% if form.cantidad.errors %}error{% endif %}">
			        {{ form.cantidad }}
			      </div>
						<div class="field {% if form.cantidad.errors %}error{% endif %}">
			        {{ form.valor_unitario }}
			      </div>
						<div class="field">
			        <button type="submit" class="ui olive fluid  button">Añadir</button>
			      </div>
					</div>
				</form>

			</div>
		</div>
		{% if items %}
		<h2 class="ui olive header">Items del Pedido {{pedido.empresa.first_name}} {{pedido.num_pedido}} <br> Express Del Norte {{pedido.npedido_express}}</h2>
		<div class="column row">
			<div class="column">
				<table class="ui very basic striped unstackable table">
					<thead>
						<tr>
							<th>Producto</th>
							<th>Cantidad</th>
							<th>Valor Unitario</th>
							<th>Valor Total</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						{% for item in items %}
							<tr>
								<td>{{ item.item.codigo }} - {{ item.item.descripcion }}</td>
								<td>{{ item.cantidad|intcomma }}</td>
								<td>${{ item.valor_unitario|intcomma }}</td>
								<td>${{ item.valor_total|intcomma }}</td>
								<td><a href="{% url 'pedido:delete_item_pedido' item.id pedido.id %}" class="ui icon green"><i class="material-icons red">delete_forever</i></a></td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
		<h2 class="ui header"></h2>
		<form action="{% url 'pedido:final_item_pedido' pedido.id %}" method="POST" class="ui form">
			{% csrf_token %}
			<input type="hidden" name="pedido" value="{{ pedido.npedido_express }}">
			<div class="two fields">
				<div class="field">
					<h3 class="ui blue header"><i class="in cart large blue icon"></i>{{ items | length}} Items - Total: ${{total|intcomma }}</h3>
				</div>
				<div class="field">
					<button type="submit" class="ui olive fluid  button">Finalizar</button>
				</div>
			</div>
		</form>
		{% else %}
		<h2 class="ui olive header">No ha agregado un items al pedido</h2>
		{% endif %}
  </div>
</div>
{% endblock %}

{% block addjs %}
<script>
	$( document ).ready(function() {
		$('.ui.dropdown').dropdown();
	});
</script>
{% endblock %}